<a href="https://colab.research.google.com/github/moha-55/humdity/blob/main/Untitled0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import time
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, classification_report

In [ ]:
# Load dataset
data_url = "https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data"
column_names = [
    "age", "workclass", "fnlwgt", "education", "education-num", "marital-status",
    "occupation", "relationship", "race", "sex", "capital-gain", "capital-loss",
    "hours-per-week", "native-country", "income"
]
data = pd.read_csv(data_url, names=column_names, na_values=" ?", skipinitialspace=True)

In [ ]:
data

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [ ]:
# Drop rows with missing values
data.dropna(inplace=True)

In [ ]:
data

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [ ]:
# Keep only 2 classes: <=50K and >50K (already binary)
# Sample 1500 rows total
data = data.sample(n=1500, random_state=42)

In [ ]:
data

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
14160,27,Private,160178,Some-college,10,Divorced,Adm-clerical,Not-in-family,White,Female,0,0,38,United-States,<=50K
27048,45,State-gov,50567,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K
28868,29,Private,185908,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,Black,Male,0,0,55,United-States,>50K
5667,30,Private,190040,Bachelors,13,Never-married,Machine-op-inspct,Not-in-family,White,Female,0,0,40,United-States,<=50K
7827,29,Self-emp-not-inc,189346,Some-college,10,Divorced,Craft-repair,Not-in-family,White,Male,2202,0,50,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20302,20,?,150084,Some-college,10,Never-married,?,Own-child,White,Male,0,0,25,United-States,<=50K
11753,45,Private,216932,Masters,14,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,40,United-States,>50K
30322,28,Private,129460,Assoc-voc,11,Married-civ-spouse,Handlers-cleaners,Wife,White,Female,0,0,30,Ecuador,<=50K
28528,38,Private,99233,Prof-school,15,Never-married,Exec-managerial,Not-in-family,White,Male,0,0,40,United-States,>50K
10881,28,?,147471,HS-grad,9,Divorced,?,Own-child,White,Female,0,0,10,United-States,<=50K

In [ ]:
data.count()

age               1500
workclass         1500
fnlwgt            1500
education         1500
education-num     1500
marital-status    1500
occupation        1500
relationship      1500
race              1500
sex               1500
capital-gain      1500
capital-loss      1500
hours-per-week    1500
native-country    1500
income            1500
dtype: int64

In [ ]:
data.describe()

,age,fnlwgt,education-num,capital-gain,capital-loss,hours-per-week
count,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000
mean,38.789333,188396.006667,10.065333,1234.520667,91.582667,40.456667
std,13.585040,103490.061623,2.605172,8114.753100,416.884932,12.246473
min,17.000000,21626.000000,1.000000,0.000000,0.000000,2.000000
25%,28.000000,117836.750000,9.000000,0.000000,0.000000,40.000000
50%,37.000000,177833.500000,10.000000,0.000000,0.000000,40.000000
75%,48.000000,235373.000000,12.000000,0.000000,0.000000,45.000000
max,90.000000,972354.000000,16.000000,99999.000000,2559.000000,99.000000

In [ ]:
# Encode categorical features
label_encoders = {}
for column in data.select_dtypes(include=['object']).columns:
    le = LabelEncoder()
    data[column] = le.fit_transform(data[column])
    label_encoders[column] = le

In [ ]:
# Split features and labels
X = data.drop("income", axis=1)
y = data["income"]

In [ ]:
# Normalize features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [ ]:
# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.25, random_state=42)

In [ ]:
# --- Classifier 1: SVM ---
print("\nTraining SVM...")
start_train = time.time()
svm_clf = SVC()
svm_clf.fit(X_train, y_train)
end_train = time.time()

start_test = time.time()
y_pred_svm = svm_clf.predict(X_test)
end_test = time.time()

print("SVM Training Time: {:.4f} seconds".format(end_train - start_train))
print("SVM Testing Time: {:.4f} seconds".format(end_test - start_test))
print("SVM Confusion Matrix:\n", confusion_matrix(y_test, y_pred_svm))

Training SVM...
SVM Training Time: 0.0361 seconds
SVM Testing Time: 0.0135 seconds
SVM Confusion Matrix:
 [[269  13]
 [ 49  44]]

In [ ]:
# --- Classifier 2: Logistic Regression ---
print("\nTraining Logistic Regression...")
start_train = time.time()
logreg_clf = LogisticRegression(max_iter=1000)
logreg_clf.fit(X_train, y_train)
end_train = time.time()

start_test = time.time()
y_pred_logreg = logreg_clf.predict(X_test)
end_test = time.time()

print("LogReg Training Time: {:.4f} seconds".format(end_train - start_train))
print("LogReg Testing Time: {:.4f} seconds".format(end_test - start_test))
print("LogReg Confusion Matrix:\n", confusion_matrix(y_test, y_pred_logreg))

Training Logistic Regression...
LogReg Training Time: 0.0234 seconds
LogReg Testing Time: 0.0007 seconds
LogReg Confusion Matrix:
 [[265  17]
 [ 50  43]]